### ISSUE TITLE
Diagram shift thus unclear

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#314] opened 2024-05-26 13:26 UTC
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-2?inDocPath=-pze619.w8vfq6.m5ggtf%7E3f9f23ed

## The issue as described by the user:
```
Diagram is shifted to the right, so one cannot make out everything in it and so it can be a biut confusing
```

## The text highlighted while reporting this issue:
```
Exact inference in
DBNs
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/probabilistic-reasoning/slides/dbn-inference.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=probabilistic-reasoning/slides/dbn-inference.en.xhtml&bindings=0_2_ftueSf10

2. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/probabilistic-reasoning/sec/DBN.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=probabilistic-reasoning/sec/DBN.en.xhtml&bindings=0_0_ewsjLS

3. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/probabilistic-reasoning/sec/temporal-models.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=probabilistic-reasoning/sec/temporal-models.en.xhtml&bindings=0_0_3pgo

4. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/course/sec/uncert.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=course/sec/uncert.en.xhtml&bindings=0_0_c

5. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/course/notes/notes2.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=course/notes/notes2.xhtml

**Comment by kohlhase** [comment] 2024-08-18 12:14
Duplicate of #347

**Closed by kohlhase** 2024-08-18 12:14 UTC
Labels: user-reported
