### ISSUE TITLE
Messy theory graph

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#183] opened 2023-12-05 11:40 UTC
A content ERROR was logged by "Marcel Schütz" at the following url:

https://courses.voll-ki.fau.de/course-view/lbs?slideNum=4&viewMode=SLIDE_MODE&audioOnly=false&sectionId=af80fa4c

## The issue as described by the user:
```
The theory graph on this slide is a huge mess...
```

## The text highlighted while reporting this issue:
```
Modular Representation of Math (Mmt
              Example)
          
              ▷Elementary Algebra and Arithmetics
```

### The selected text was in the following section hierarchy:

1. GitLab: https://gl.mathhub.info/MiKoMH/talks/-/blob/main/source/mmt/slides/elalg-nat-graph.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/talks&filepath=mmt/slides/elalg-nat-graph.en.xhtml

**Comment by kohlhase** [comment] 2024-08-18 12:17
Duplicate of #347

**Closed by kohlhase** 2024-08-18 12:17 UTC
Labels: user-reported
