### ISSUE TITLE
Diagram slide is messed up

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#339] opened 2024-07-31 18:37 UTC
A content ERROR was logged by "Shamseldin Elkhatib" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-2?inDocPath=wyrfm9.-dpk62k.-zcxmh2%7Ed3351b0a

## The issue as described by the user:
```
The diagram is all over the slide. 
```

## The text highlighted while reporting this issue:
```
Start with an example classified as both positive and negative
(Need a contradiction)
          
        
        2.Invent clauses that resolve with a fact in our knowledge base

        
        
                                    
                                      
                                        
                                          ¬parent(𝑥,𝑧)∨¬parent(𝑧,𝑦)∨grandparent(𝑥,𝑦)  
                                          parent(𝐺𝑒𝑜𝑟𝑔𝑒,𝐸𝑙𝑖𝑧𝑎𝑏𝑒𝑡ℎ)  
                                          ¬parent(𝐸𝑙𝑖𝑧𝑎𝑏𝑒𝑡ℎ,𝑦)∨grandparent(𝐺𝑒𝑜𝑟𝑔𝑒,𝑦)  
                                          parent(𝐸𝑙𝑖𝑧𝑎𝑏𝑒𝑡ℎ,𝐴𝑛𝑛𝑒)  
                                          grandparent(𝐺𝑒𝑜𝑟𝑔𝑒,𝐴𝑛𝑛𝑒)  
                                          ¬grandparent(𝐺𝑒𝑜𝑟𝑔𝑒,𝐴𝑛𝑛𝑒)  
                                          {}
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/ml/slides/IR-ex.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=ml/slides/IR-ex.en.xhtml&bindings=0_4_4dlw5YfOWUi

2. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/ml/sec/IR.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=ml/sec/IR.en.xhtml&bindings=0_3_3XgCxkLqc

3. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/ml/sec/ILP.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=ml/sec/ILP.en.xhtml&bindings=0_0_TKgQY

4. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/ml/sec/ml-knowledge.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=ml/sec/ml-knowledge.en.xhtml&bindings=0_0_S0gk

5. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/course/sec/ml.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=course/sec/ml.en.xhtml&bindings=0_0_3a

6. GitLab: https://gl.mathhub.info/courses/FAU/AI/course/-/blob/main/source/course/notes/notes2.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=courses/FAU/AI/course&filepath=course/notes/notes2.xhtml

**Comment by kohlhase** [comment] 2024-08-18 12:14
Duplicate of #347

**Closed by kohlhase** 2024-08-18 12:14 UTC
Labels: user-reported
