### ISSUE TITLE
ERROR in intro/slides/four-answers.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#34] opened 2022-12-15 09:33 UTC
A content ERROR was logged by a user at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=wjkxob

## The issue as described by the user:
```
Text overlapped. Affecting readability.
```

## The text highlighted while reporting this issue:
```
formalization
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/intro/slides/four-answers.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=intro/slides/four-answers.en.xhtml

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/rational-agents/sec/intro.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=rational-agents/sec/intro.en.xhtml

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/rational-agents/sec/rational-agents.en.tex<br/>FetchURL: /:sTeX/fulldocument?archive=MiKoMH/AI&filepath=rational-agents/sec/rational-agents.en.xhtml

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes.tex<br/>FetchURL: :sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes.xhtml

**Comment by Jazzpirate** [comment] 2022-12-15 09:41
The problem is that the `paragraph` in the table does not do line breaks, and none of the `overlow`-CSS values seem to change that (see
https://stexmmt.mathhub.info/:sTeX/browser/fulldocument?archive=MiKoMH/AI&filepath=intro/slides/four-answers.en.xhtml )... any idea what I need to do to the `paragraph`-class for the content to properly break text?

**Comment by abchugh** [comment] 2022-12-15 16:58
The table has `white-space: nowrap;` set (`rustex.css`). Probably what's causing the mess. Removing it causes a bigger mess though :/

**Comment by Jazzpirate** [comment] 2022-12-15 17:27
ah! That helps. Yes, tables shouldn't break at white spaces, but paragraphs should, so adding `white-space: normal` to the `paragraph`-class improves things significantly!

**Comment by Jazzpirate** [comment] 2022-12-15 17:45
closing this for now; will be fixed (or at least improved) with the next rustex/MMT/frontend versions

**Closed by Jazzpirate** 2022-12-15 17:45 UTC
Labels: user-reported
