### ISSUE TITLE
Tree below not readable

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#268] opened 2024-03-20 08:37 UTC
A content ERROR was logged by "Luca Becker" at the following url:

https://courses.voll-ki.fau.de/course-notes/ai-1?inDocPath=uqur5k.-9gxrd5.onmsqh%7E5a8292e2

## The issue as described by the user:
```
The Tree on this slide is not readable. All text is stuffed in the top left corner.
```

## The text highlighted while reporting this issue:
```
Pruning
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/slides/alpha-idea.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/slides/alpha-idea.en.xhtml&bindings=0_0_VxLWJ0

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/alphabeta.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/alphabeta.en.xhtml&bindings=0_0_3AZ7xO

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/game-play/sec/game-play.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=game-play/sec/game-play.en.xhtml&bindings=0_0_d4U

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/sec/gps.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/sec/gps.en.xhtml&bindings=0_0_3a

5. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes1.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes1.xhtml

**Comment by kohlhase** [comment] 2024-08-18 12:15
Duplicate of #347

**Closed by kohlhase** 2024-08-18 12:15 UTC
Labels: user-reported
