### ISSUE TITLE
User reported ERROR rational-decisions/slides/sequential-decision-problems.en.xhtml

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#95] opened 2023-05-23 14:17 UTC
A content ERROR was logged by "a user" at the following url:

https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes2.xhtml?inDocPath=y754bv.drfmv0%7Eb437ded6

## The issue as described by the user:
```
doesnt look right
```

## The text highlighted while reporting this issue:
```
Search  
                                Planning  
                                
                                                    Decision-theoretic Planning
                                                    
                                
                                                    Markov Decision Problems
                                                      (MDPs)
                                                    
                                
                                                    Partially observable MDPs
                                                      (POMDPs)
```

### The selected text was in the following section hierarchy:

**_INNERMOST SECTION FIRST_**

1. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/rational-decisions/slides/sequential-decision-problems.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=rational-decisions/slides/sequential-decision-problems.en.xhtml&bindings=0_1_ewsjB4

2. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/rational-decisions/sec/sequential-decision-problems.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=rational-decisions/sec/sequential-decision-problems.en.xhtml&bindings=0_1_UhgIW

3. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/rational-decisions/sec/complex-decisions.en.tex<br/>FetchURL: https://stexmmt.mathhub.info//:sTeX/fulldocument?archive=MiKoMH/AI&filepath=rational-decisions/sec/complex-decisions.en.xhtml&bindings=0_0_Sweg

4. GitLab: https://gl.mathhub.info/MiKoMH/AI/-/blob/main/source/course/notes/notes2.tex<br/>FetchURL: https://stexmmt.mathhub.info/:sTeX/fulldocument?archive=MiKoMH/AI&filepath=course/notes/notes2.xhtml

**Comment by kohlhase** [comment] 2023-05-23 17:56
TIKZ graphics are always a problem. At the moment we cannot really do better. Assigning to Dennis, who is the only one who can maybe help.

**Comment by kohlhase** [comment] 2024-08-18 12:20
Duplicate of #347

**Closed by kohlhase** 2024-08-18 12:20 UTC
Labels: user-reported
